name: buhuiwangshi
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  animated_toggle_switch: ^0.8.3
  custom_navigation_bar: ^0.8.2
  day_night_time_picker: ^1.3.1
  easy_date_timeline: ^1.1.3
  flutter_smart_dialog: ^4.9.8+1
  flutter_material_color_picker: ^1.2.0
  provider: ^6.1.2
  jiffy: ^6.3.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  uuid: ^4.5.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
